### ISSUE TITLE
documentation describing required location of beam-wallet.cfg and beam-node.cfg is incorrect

### ISSUE THREAD

**Issue by taw00** [BeamMW/beam-docs#2]
In several places in the docs it is mentioned that the .cfg file is looked for in the  "same folder as Beam Node binary" for example.

This is incorrect. The .cfg is searched for in your current working directory and not in the location of the executable. At least on linux.

I.e., If I am in my home directory and I run BeamWallet or beam-node (and the executable is in /usr/bin for example) it looks for the .cfg in the home directory. If I switch to any other directory and run from there... the .cfg is expected to be in the new current working directory. If you run BeamWallet from the desktop menus --assuming you have it correctly configured for that (for example, from the GNOME launcher)-- the default working directory generally becomes the user's home directory (though sometimes the process for other applications will kick the pwd to root /).

Anyway. The docs are a bit misleading on this point. Thanks! -t
_(t0dd on discord and lots of other places)_

**Comment by Jagor21** [comment]
fixed
